# missing values

In [61]:
import pandas as pd
import numpy as np
import seaborn as sns

In [3]:
# we have taken this dataset from analytics vidhya 
# loan prediction dataset
# for practising purpose because it conatains missing values

df = pd.read_csv('./train_ctrUa4K.csv')
df.head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
0  LP001002   Male      No          0      Graduate            No   
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   

   Credit_History Property_Area Loan_Status  
0             1.0         Urban           Y  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y

In [5]:
df.shape

(614, 13)

In [14]:
# it has many null values 

df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [16]:
# total number of missing values in dataset

df.isnull().sum().sum()

149

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   Loan_ID            614 non-null    object 
 1   Gender             601 non-null    object 
 2   Married            611 non-null    object 
 3   Dependents         599 non-null    object 
 4   Education          614 non-null    object 
 5   Self_Employed      582 non-null    object 
 6   ApplicantIncome    614 non-null    int64  
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object 
 12  Loan_Status        614 non-null    object 
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB


In [12]:
df.nunique()

Loan_ID              614
Gender                 2
Married                2
Dependents             4
Education              2
Self_Employed          2
ApplicantIncome      505
CoapplicantIncome    287
LoanAmount           203
Loan_Amount_Term      10
Credit_History         2
Property_Area          3
Loan_Status            2
dtype: int64

### Types of missing values

    missing completely at random : The probability of missing the data is same for all the observatins. There is no relationship between observed and missed values they are completely random

    missing at random : missing values might have relationship with another feature . for example we have gender and age . it is possible that some females will not give their age so most missing values of age might be of female 

    missing not at random : missing values depend on the unobserved data . there is some pattern in missing data which observed data cannot tell. for example in a survey a people with less income may not give their salary information.

### Two ways to handle missing data

    1) Deleting the Missing values
    2) Imputing the Missing Values

## Deleting missing values

    If the missing value is of the type Missing Not At Random (MNAR), then it should not be deleted.

    If the missing value is of type Missing At Random (MAR) or Missing Completely At Random (MCAR) then it can be deleted.
    if dataset contains important data then this method should not be used

### drop rows with missing values

In [18]:
df.dropna(axis=0).head()

Loan_ID Gender Married Dependents     Education Self_Employed  \
1  LP001003   Male     Yes          1      Graduate            No   
2  LP001005   Male     Yes          0      Graduate           Yes   
3  LP001006   Male     Yes          0  Not Graduate            No   
4  LP001008   Male      No          0      Graduate            No   
5  LP001011   Male     Yes          2      Graduate           Yes   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
1             4583             1508.0       128.0             360.0   
2             3000                0.0        66.0             360.0   
3             2583             2358.0       120.0             360.0   
4             6000                0.0       141.0             360.0   
5             5417             4196.0       267.0             360.0   

   Credit_History Property_Area Loan_Status  
1             1.0         Rural           N  
2             1.0         Urban           Y  
3             1.0         Urban           Y  
4             1.0         Urban           Y  
5             1.0         Urban           Y

In [19]:
df.dropna(axis=0).isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

### dropping columns which have many missing values

In [23]:
# drop credit history

df.drop('Credit_History', axis=1).head(2)

Loan_ID Gender Married Dependents Education Self_Employed  \
0  LP001002   Male      No          0  Graduate            No   
1  LP001003   Male     Yes          1  Graduate            No   

   ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0             5849                0.0         NaN             360.0   
1             4583             1508.0       128.0             360.0   

  Property_Area Loan_Status  
0         Urban           Y  
1         Rural           N

In [25]:
df.drop('Credit_History', axis=1).isnull().sum().sum()

# now we have only 99 missing values

99

## Imputing the Missing Value


### Replacing With Arbitrary Value

    making an educated guess and replacing values

In [30]:
# making null dependents value 0

df.Dependents.fillna(value=0, inplace=True)

In [31]:
df.Dependents.isnull().sum()

0

### Replacing with mean

    we will use this in case of numerical columns
    Do not use mean when we have outliers (first handle outliers)

In [33]:
df.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents            0
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [36]:
df.LoanAmount.fillna(df.LoanAmount.mean(), inplace=True) # replacing Loan_amount with mean
df.Credit_History.fillna(df.Credit_History.mean(), inplace=True) # replacing credit history with mean

In [38]:
df.isnull().sum().sum()

62

### Replacing with Mode

    Use mode in categorical values

In [41]:
# This can be used on Gender, married and self_employed

df.Gender.fillna(df.Gender.mode()[0], inplace=True)
df.Self_Employed.fillna(df.Self_Employed.mode()[0], inplace=True)
df.Married.fillna(df.Married.mode()[0], inplace=True)

In [45]:
df.isnull().sum().sum()

14

### Replacing with median

    used in the case of outliers

In [ ]:
# replace Loan_Amount_Term

df.Loan_Amount_Term.fillna(df.Loan_Amount_Term.median(), inplace=True)

### Forward fill and Backward fill

    Mostly Used in time-series data
        forward fill : fill na values with previous values
        backward fill : fill na values with next values

In [53]:
ser = pd.Series(range(8))
ser[1:3] = np.nan
ser

0    0.0
1    NaN
2    NaN
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
dtype: float64

In [54]:
# forward fill

ser.fillna(method='ffill')

0    0.0
1    0.0
2    0.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
dtype: float64

In [55]:
# backward fill

ser.fillna(method='bfill')

0    0.0
1    3.0
2    3.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
dtype: float64

### Interpolation

    values can be interpolated

In [56]:
ser.interpolate()

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
5    5.0
6    6.0
7    7.0
dtype: float64

## using ci-kit learn Library

### Replacing value with mean , median or mode | univariate

In [57]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x = [[np.nan, 2], [np.nan, 6], [9, 10]]

In [59]:
imputer.fit(x)

SimpleImputer()

In [60]:
imputer.transform(x)

array([[ 9.,  2.],
       [ 9.,  6.],
       [ 9., 10.]])

### IterativeImputer | multivariate

    In this method when one column dependes on another column for some reason we can use this method
    
    IterativeImputer uses regression to find the missing values

In [64]:
# lets load titanic dataset

titanic = sns.load_dataset('titanic')[0:7]
cols = ['sibsp', 'fare', 'age']
titanic = titanic[cols]
titanic

sibsp     fare   age
0      1   7.2500  22.0
1      1  71.2833  38.0
2      0   7.9250  26.0
3      1  53.1000  35.0
4      0   8.0500  35.0
5      0   8.4583   NaN
6      0  51.8625  54.0

In [65]:
# lets consider fare is related with age , higher the age higher is the fair

from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
imputer = IterativeImputer()
imputer.fit(titanic)

IterativeImputer()

In [66]:
# IterativeImputer it uses regression to find the target (age) using sibsp and fare columns to train the model

imputer.fit_transform(titanic)

array([[ 1.        ,  7.25      , 22.        ],
       [ 1.        , 71.2833    , 38.        ],
       [ 0.        ,  7.925     , 26.        ],
       [ 1.        , 53.1       , 35.        ],
       [ 0.        ,  8.05      , 35.        ],
       [ 0.        ,  8.4583    , 30.54136111],
       [ 0.        , 51.8625    , 54.        ]])

### KNNImputer | multivariate

    It uses k nearest neighbour to find the missing values

In [68]:
from sklearn.impute import KNNImputer
impute_knn = KNNImputer(n_neighbors=2)
impute_knn.fit_transform(titanic)

array([[ 1.    ,  7.25  , 22.    ],
       [ 1.    , 71.2833, 38.    ],
       [ 0.    ,  7.925 , 26.    ],
       [ 1.    , 53.1   , 35.    ],
       [ 0.    ,  8.05  , 35.    ],
       [ 0.    ,  8.4583, 30.5   ],
       [ 0.    , 51.8625, 54.    ]])

### missing value indicator 

    Just to indicate that the we have imputed the missing value we can use an indicator. lets say a column which is a good for predicting target variable then we can use indicator to indicate that this value is missing and we have imputed it

In [69]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(add_indicator=True)
imputer.fit_transform(titanic)

# 1 is indicating that we have iputed the missing value

array([[ 1.    ,  7.25  , 22.    ,  0.    ],
       [ 1.    , 71.2833, 38.    ,  0.    ],
       [ 0.    ,  7.925 , 26.    ,  0.    ],
       [ 1.    , 53.1   , 35.    ,  0.    ],
       [ 0.    ,  8.05  , 35.    ,  0.    ],
       [ 0.    ,  8.4583, 35.    ,  1.    ],
       [ 0.    , 51.8625, 54.    ,  0.    ]])